#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
rm zeroprep 0  -r
cp -r zero 0 > /dev/null 2>&1
runApplication blockMesh
#runApplication setSet -batch createObstacle.setSet
runApplication topoSet
refineMesh -overwrite -dict system/refineMeshDict
topoSet -dict system/topoSetDict2
refineMesh -overwrite -dict system/refineMeshDict2
#runApplication subsetMesh -overwrite c0 -patch walls
runApplication setFields
funkySetFields -time 0
runApplication decomposePar
cp -r 0 zeroprep
#runApplication `getApplication`
#runParallel `getApplication`
#------------------------------------------------------------------------------
